spring:
  data:
    mongodb:
      authentication-database: morphia
      database: morphia

      uri: mongodb://localhost:27017
  jackson:
    serialization:
      INDENT_OUTPUT: true
      
logging:
  level:
    root: info
    botalibrium: debug
